- name: add Tomcat group
  group:
    name: "{{ tomcat_group }}"
    state: present
  tags: install

- name: add Tomcat user
  user:
    name: "{{ tomcat_owner }}"
    comment: Kill Bill Tomcat owner
    group: "{{ tomcat_group }}"
    create_home: yes
    home: "{{ tomcat_home }}"
    state: present
  tags: install

- name: install Tomcat
  become: true
  unarchive:
    src: "http://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    remote_src: True
    dest: "{{ tomcat_install_dir }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
  tags: install

- name: symlink install directory
  file: src="{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}" path="{{ catalina_home }}" state=link
  tags: install

# The individual files have the correct permissions already, but not the top directory
- name: set correct permissions
  become: true
  file: path={{ catalina_home }} owner={{ tomcat_owner }} group={{ tomcat_group }}
  tags: install
