---
- name: check Tomcat PID file
  stat: path="{{ catalina_base }}/tomcat.pid"
  register: tomcat_pid
  when:
    - catalina_home is defined
  tags: stop

- name: stop Tomcat (with PID file)
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
    CATALINA_PID: "{{ catalina_base }}/tomcat.pid"
  command: "{{ catalina_home }}/bin/catalina.sh stop 30 -force"
  ignore_errors: True
  when:
    - catalina_home is defined
    - tomcat_pid is not defined or tomcat_pid.stat.exists == True
  tags: stop

- name: stop Tomcat (without PID file)
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
  command: "{{ catalina_home }}/bin/catalina.sh stop 30 -force"
  ignore_errors: True
  when:
    - catalina_home is defined
    - tomcat_pid is not defined or tomcat_pid.stat.exists == False
  tags: stop

- name: check if war file exists
  stat:
    path: "{{ catalina_base }}/{{ kb_webapps }}/ROOT.war"
  register: war
  tags:
    - tomcat_cleanup
    - stop

- name: clean up Tomcat deployment files
  become: true
  become_user: "{{ tomcat_owner }}"
  file: path={{ catalina_base }}/{{ item }} state=absent
  with_items:
    - "{{ kb_webapps }}/ROOT"
    - work/
  when:
    - catalina_home is defined
    - war.stat.exists
  tags:
    - tomcat_cleanup
    - stop
