---
- name: Deploy Tomcat
  hosts: all
  vars:
    tomcat_version: 8.5.59
  become: yes
  tasks:
    - name: install Tomcat
      import_tasks: roles/tomcat/tasks/install.yml
    - name: install Tomcat native libraries
      import_tasks: roles/tomcat/tasks/native.yml
      when:
        - apr_config_path is defined
        - java_home is defined
    - name: setup Tomcat
      import_tasks: roles/tomcat/tasks/main.yml
