name: release

on:
  workflow_dispatch:
    inputs:
      killbill_version:
        description: 'killbill version'
        required: false
        default: ''
      kaui_version:
        description: 'kaui version'
        required: false
        default: ''
      cloud_version:
        description: 'killbill-cloud version'
        required: true
        default: 'master'

jobs:
  docker:
    name: Publish Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push killbill/base:latest
        run: |
          TAG="killbill/base:latest"
          cd docker/templates/base/latest
          DOCKER_BUILDKIT=1 docker build --no-cache -t $TAG -f Dockerfile --build-arg KILLBILL_CLOUD_VERSION=${{ github.event.inputs.cloud_version }} .
          docker push $TAG
      - name: Build and push latest images
        run: |
          cd docker
          make -e TARGET=kaui -e VERSION=latest rebuild
          make -e TARGET=killbill VERSION=latest rebuild
          docker push killbill/kaui:latest
          docker push killbill/killbill:latest
      - name: Build and push killbill image
        if: github.event.inputs.killbill_version != ''
        run: |
          cd docker
          make -e TARGET=killbill VERSION=${{ github.event.inputs.killbill_version }} rebuild
          docker push killbill/killbill:${{ github.event.inputs.killbill_version }}
      - name: Build and push kaui image
        if: github.event.inputs.kaui_version != ''
        run: |
          cd docker
          make -e TARGET=kaui -e VERSION=${{ github.event.inputs.kaui_version }} rebuild
          docker push killbill/kaui:${{ github.event.inputs.kaui_version }}
