name: release

on:
  push:
    branches:
      - release

env:
  KILLBILL_VERSION: 0.22.18
  KAUI_VERSION: 2.0.5
  KILLBILL_CLOUD_VERSION: master

jobs:
  docker:
    name: Publish Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push killbill/base:latest
        run: |
          TAG="killbill/base:latest"
          cd docker/templates/base/latest
          DOCKER_BUILDKIT=1 docker build --no-cache -t $TAG -f Dockerfile --build-arg KILLBILL_CLOUD_VERSION=$KILLBILL_CLOUD_VERSION .
          docker push $TAG
      - name: Build and push common images
        run: |
          cd docker
          make -e TARGET=kaui -e VERSION=latest rebuild
          make -e TARGET=kaui -e VERSION=$KAUI_VERSION rebuild
          make -e TARGET=killbill VERSION=latest rebuild
          make -e TARGET=killbill VERSION=$KILLBILL_VERSION rebuild
          docker push killbill/kaui:latest
          docker push killbill/kaui:$KAUI_VERSION
          docker push killbill/killbill:latest
          docker push killbill/killbill:$KILLBILL_VERSION
